// Package payment Code generated by swaggo/swag. DO NOT EDIT
package payment

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bank/all": {
            "get": {
                "description": "Lấy danh sách ngân hàng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bank"
                ],
                "summary": "Lấy danh sách ngân hàng",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment.BankList"
                        }
                    }
                }
            }
        },
        "/payment-methods": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách phương thức thanh toán",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Lấy danh sách phương thức thanh toán",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "getPaymentMethodsRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.GetPaymentMethodsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Danh sách phương thức thanh toán",
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentMethodList"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật phương thức thanh toán",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Cập nhật phương thức thanh toán",
                "parameters": [
                    {
                        "description": "Phương thức thanh toán",
                        "name": "paymentMethod",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentMethod"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Phương thức thanh toán",
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentMethod"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo phương thức thanh toán",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Tạo phương thức thanh toán",
                "parameters": [
                    {
                        "description": "Phương thức thanh toán",
                        "name": "paymentMethod",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentMethod"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Phương thức thanh toán",
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentMethod"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xóa phương thức thanh toán",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Xóa phương thức thanh toán",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "deletePaymentMethodRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.DeletePaymentMethodRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Phương thức thanh toán",
                        "schema": {
                            "$ref": "#/definitions/payment.Empty"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/sepay/webhook": {
            "post": {
                "description": "Webhook thanh toán Sepay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Webhook thanh toán Sepay",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "sepayWebhookRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.SepayWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhook thanh toán Sepay",
                        "schema": {
                            "$ref": "#/definitions/payment.Empty"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/transaction-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách loại giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Lấy danh sách loại giao dịch",
                "parameters": [
                    {
                        "description": "Empty request",
                        "name": "empty",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.Empty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Danh sách loại giao dịch",
                        "schema": {
                            "$ref": "#/definitions/payment.TransactionTypeList"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật loại giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Cập nhật loại giao dịch",
                "parameters": [
                    {
                        "description": "Loại giao dịch",
                        "name": "transactionType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.TransactionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loại giao dịch",
                        "schema": {
                            "$ref": "#/definitions/payment.TransactionType"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo loại giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Tạo loại giao dịch",
                "parameters": [
                    {
                        "description": "Loại giao dịch",
                        "name": "transactionType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.TransactionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loại giao dịch",
                        "schema": {
                            "$ref": "#/definitions/payment.TransactionType"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xóa loại giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Xóa loại giao dịch",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "deleteTransactionTypeRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.DeleteTransactionTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loại giao dịch",
                        "schema": {
                            "$ref": "#/definitions/payment.Empty"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy dashboard ví",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Lấy dashboard ví",
                "parameters": [
                    {
                        "description": "Empty request",
                        "name": "empty",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.Empty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet dashboard",
                        "schema": {
                            "$ref": "#/definitions/payment.WalletDashboard"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/deposit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Nạp tiền",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Nạp tiền",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "depositRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Giao dịch nạp tiền",
                        "schema": {
                            "$ref": "#/definitions/payment.WalletTransaction"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/payment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Tạo giao dịch",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "paymentRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Giao dịch",
                        "schema": {
                            "$ref": "#/definitions/payment.WalletTransaction"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách giao dịch ví",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Lấy danh sách giao dịch ví",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "getWalletTransactionsRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.GetWalletTransactionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Danh sách giao dịch ví",
                        "schema": {
                            "$ref": "#/definitions/payment.WalletTransactionList"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xuất dữ liệu ví",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Xuất dữ liệu ví",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ví",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "reportRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dữ liệu ví",
                        "schema": {
                            "$ref": "#/definitions/payment.ExportResponse"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}/report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy báo cáo ví",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Lấy báo cáo ví",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ví",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "reportRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Báo cáo ví",
                        "schema": {
                            "$ref": "#/definitions/payment.ReportResponse"
                        }
                    },
                    "400": {
                        "description": "Lỗi yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "$ref": "#/definitions/status.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "payment.Bank": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "payment.BankList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payment.Bank"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "payment.DeletePaymentMethodRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "payment.DeleteTransactionTypeRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "payment.DepositRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "externalPaymentId": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "string"
                },
                "walletId": {
                    "type": "integer"
                }
            }
        },
        "payment.Empty": {
            "type": "object"
        },
        "payment.ExportResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "format": {
                    "type": "string"
                }
            }
        },
        "payment.GetPaymentMethodsRequest": {
            "type": "object",
            "properties": {
                "organizationId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "payment.GetWalletTransactionsRequest": {
            "type": "object",
            "properties": {
                "fromDate": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "toDate": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "payment.PaymentMethod": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "payment.PaymentMethodList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payment.PaymentMethod"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "payment.PaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "relatedId": {
                    "type": "string"
                },
                "relatedService": {
                    "type": "string"
                },
                "walletId": {
                    "type": "integer"
                }
            }
        },
        "payment.ReportRequest": {
            "type": "object",
            "properties": {
                "fromDate": {
                    "type": "string"
                },
                "toDate": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "walletId": {
                    "type": "integer"
                }
            }
        },
        "payment.ReportResponse": {
            "type": "object",
            "properties": {
                "totalAmount": {
                    "type": "number"
                },
                "totalTransactions": {
                    "type": "integer"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payment.WalletTransaction"
                    }
                }
            }
        },
        "payment.SepayWebhookRequest": {
            "type": "object",
            "properties": {
                "AccountNumber": {
                    "type": "string"
                },
                "Accumulated": {
                    "type": "number"
                },
                "Code": {
                    "type": "string"
                },
                "Content": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Gateway": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "ReferenceCode": {
                    "type": "string"
                },
                "SubAccount": {
                    "type": "string"
                },
                "TransactionDate": {
                    "type": "string"
                },
                "TransferAmount": {
                    "type": "number"
                },
                "TransferType": {
                    "type": "string"
                }
            }
        },
        "payment.TransactionType": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "payment.TransactionTypeList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payment.TransactionType"
                    }
                }
            }
        },
        "payment.WalletDashboard": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "balance": {
                    "type": "number"
                },
                "pendingTransactions": {
                    "type": "integer"
                },
                "totalExpense": {
                    "type": "number"
                },
                "totalIncome": {
                    "type": "number"
                }
            }
        },
        "payment.WalletTransaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "externalPaymentId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "relatedId": {
                    "type": "string"
                },
                "relatedService": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionCode": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "walletId": {
                    "type": "integer"
                }
            }
        },
        "payment.WalletTransactionList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payment.WalletTransaction"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "status.Error": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2/payment",
	Schemes:          []string{"http"},
	Title:            "Payment Service",
	Description:      "Payment Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
