# Chọn image Python cơ bản
FROM python:3.11-slim

# Set UTF-8 locale để đọc/write UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONIOENCODING=utf-8

# Cập nhật apt và cài các gói cần thiết cho zbar và tesseract
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libzbar-dev \
    pkg-config \
    libjpeg-dev \
    zlib1g-dev \
    libzbar0 \
    libpng-dev \
    tesseract-ocr \
    tesseract-ocr-eng \
    tesseract-ocr-vie \
    && rm -rf /var/lib/apt/lists/*

# Tạo thư mục app
WORKDIR /app

# Copy requirements nếu có
COPY requirements.txt .

# Cài các thư viện Python
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Command mặc định
CMD ["python", "http_server.py"]
