root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp/air"

[build]
  bin = "./.tmp/air/file-service"
  cmd = "go build -o ./.tmp/air/file-service ."
  delay = 1000
  exclude_dir = [".tmp", "bin", "assets", "vendor", "testdata", "docs"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "yml", "yaml"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
