// Package transaction Code generated by swaggo/swag. DO NOT EDIT
package transaction

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TransactionService"
                ],
                "summary": "Lấy danh sách giao dịch",
                "parameters": [
                    {
                        "enum": [
                            0,
                            10,
                            20,
                            30,
                            40,
                            50,
                            60,
                            70,
                            80
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "TransactionMethod_TRANSACTION_METHOD_BUY": "Mua",
                            "TransactionMethod_TRANSACTION_METHOD_COST": "Chi phí",
                            "TransactionMethod_TRANSACTION_METHOD_DEPOSIT": "Đặt cọc",
                            "TransactionMethod_TRANSACTION_METHOD_INVESTMENT": "Góp vốn",
                            "TransactionMethod_TRANSACTION_METHOD_RENT": "Cho thuê",
                            "TransactionMethod_TRANSACTION_METHOD_REVENUE": "Thu nhập",
                            "TransactionMethod_TRANSACTION_METHOD_SALE": "Bán",
                            "TransactionMethod_TRANSACTION_METHOD_SIGN": "Ký hợp đồng"
                        },
                        "x-enum-varnames": [
                            "TransactionMethod_TRANSACTION_METHOD_UNKNOWN",
                            "TransactionMethod_TRANSACTION_METHOD_SIGN",
                            "TransactionMethod_TRANSACTION_METHOD_COST",
                            "TransactionMethod_TRANSACTION_METHOD_REVENUE",
                            "TransactionMethod_TRANSACTION_METHOD_INVESTMENT",
                            "TransactionMethod_TRANSACTION_METHOD_DEPOSIT",
                            "TransactionMethod_TRANSACTION_METHOD_RENT",
                            "TransactionMethod_TRANSACTION_METHOD_SALE",
                            "TransactionMethod_TRANSACTION_METHOD_BUY"
                        ],
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            10,
                            20,
                            30
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "TransactionStatus_TRANSACTION_STATUS_APPROVED": "Đã xác nhận",
                            "TransactionStatus_TRANSACTION_STATUS_PENDING": "Chờ xác nhận",
                            "TransactionStatus_TRANSACTION_STATUS_REJECTED": "Từ chối"
                        },
                        "x-enum-varnames": [
                            "TransactionStatus_TRANSACTION_STATUS_UNKNOWN",
                            "TransactionStatus_TRANSACTION_STATUS_PENDING",
                            "TransactionStatus_TRANSACTION_STATUS_APPROVED",
                            "TransactionStatus_TRANSACTION_STATUS_REJECTED"
                        ],
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "toId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            10,
                            20,
                            30,
                            40
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "OwnerType_OWNER_TYPE_DEAL": "Thương vụ",
                            "OwnerType_OWNER_TYPE_GROUP": "Nhóm",
                            "OwnerType_OWNER_TYPE_ORGANIZATION": "Tổ chức",
                            "OwnerType_OWNER_TYPE_USER": "Người dùng"
                        },
                        "x-enum-varnames": [
                            "OwnerType_OWNER_TYPE_UNKNOWN",
                            "OwnerType_OWNER_TYPE_USER",
                            "OwnerType_OWNER_TYPE_GROUP",
                            "OwnerType_OWNER_TYPE_ORGANIZATION",
                            "OwnerType_OWNER_TYPE_DEAL"
                        ],
                        "name": "toOf",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction list",
                        "schema": {
                            "$ref": "#/definitions/transactionpb.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/{id}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Duyệt giao dịch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TransactionService"
                ],
                "summary": "Duyệt giao dịch",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction approved successfully",
                        "schema": {
                            "$ref": "#/definitions/transactionpb.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "transactionpb.OwnerType": {
            "type": "integer",
            "enum": [
                0,
                10,
                20,
                30,
                40
            ],
            "x-enum-comments": {
                "OwnerType_OWNER_TYPE_DEAL": "Thương vụ",
                "OwnerType_OWNER_TYPE_GROUP": "Nhóm",
                "OwnerType_OWNER_TYPE_ORGANIZATION": "Tổ chức",
                "OwnerType_OWNER_TYPE_USER": "Người dùng"
            },
            "x-enum-varnames": [
                "OwnerType_OWNER_TYPE_UNKNOWN",
                "OwnerType_OWNER_TYPE_USER",
                "OwnerType_OWNER_TYPE_GROUP",
                "OwnerType_OWNER_TYPE_ORGANIZATION",
                "OwnerType_OWNER_TYPE_DEAL"
            ]
        },
        "transactionpb.TransactionMethod": {
            "type": "integer",
            "enum": [
                0,
                10,
                20,
                30,
                40,
                50,
                60,
                70,
                80
            ],
            "x-enum-comments": {
                "TransactionMethod_TRANSACTION_METHOD_BUY": "Mua",
                "TransactionMethod_TRANSACTION_METHOD_COST": "Chi phí",
                "TransactionMethod_TRANSACTION_METHOD_DEPOSIT": "Đặt cọc",
                "TransactionMethod_TRANSACTION_METHOD_INVESTMENT": "Góp vốn",
                "TransactionMethod_TRANSACTION_METHOD_RENT": "Cho thuê",
                "TransactionMethod_TRANSACTION_METHOD_REVENUE": "Thu nhập",
                "TransactionMethod_TRANSACTION_METHOD_SALE": "Bán",
                "TransactionMethod_TRANSACTION_METHOD_SIGN": "Ký hợp đồng"
            },
            "x-enum-varnames": [
                "TransactionMethod_TRANSACTION_METHOD_UNKNOWN",
                "TransactionMethod_TRANSACTION_METHOD_SIGN",
                "TransactionMethod_TRANSACTION_METHOD_COST",
                "TransactionMethod_TRANSACTION_METHOD_REVENUE",
                "TransactionMethod_TRANSACTION_METHOD_INVESTMENT",
                "TransactionMethod_TRANSACTION_METHOD_DEPOSIT",
                "TransactionMethod_TRANSACTION_METHOD_RENT",
                "TransactionMethod_TRANSACTION_METHOD_SALE",
                "TransactionMethod_TRANSACTION_METHOD_BUY"
            ]
        },
        "transactionpb.TransactionResponse": {
            "type": "object",
            "properties": {
                "method": {
                    "$ref": "#/definitions/transactionpb.TransactionMethod"
                },
                "note": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/transactionpb.TransactionStatus"
                },
                "transactionId": {
                    "type": "integer"
                },
                "transactionName": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "transactionpb.TransactionStatus": {
            "type": "integer",
            "enum": [
                0,
                10,
                20,
                30
            ],
            "x-enum-comments": {
                "TransactionStatus_TRANSACTION_STATUS_APPROVED": "Đã xác nhận",
                "TransactionStatus_TRANSACTION_STATUS_PENDING": "Chờ xác nhận",
                "TransactionStatus_TRANSACTION_STATUS_REJECTED": "Từ chối"
            },
            "x-enum-varnames": [
                "TransactionStatus_TRANSACTION_STATUS_UNKNOWN",
                "TransactionStatus_TRANSACTION_STATUS_PENDING",
                "TransactionStatus_TRANSACTION_STATUS_APPROVED",
                "TransactionStatus_TRANSACTION_STATUS_REJECTED"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2/transaction",
	Schemes:          []string{},
	Title:            "Transaction Service",
	Description:      "Transaction Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
