syntax = "proto3";

import "google/api/annotations.proto";
package chatpb;

option go_package = "pb/types/chat;chatpb";


enum ImageType {
    IMAGE_TYPE_UNSPECIFIED = 0;
    JPEG = 1;
    PNG = 2;
    GIF = 3;
}
service BackgroundImageService {
    rpc CreateBackgroundImage(CreateBackgroundImageRequest) returns (CreateBackgroundImageResponse){
        option (google.api.http) = {
            post: "/v2/chat/background"
            body: "*"
        };
    };
    rpc GetBackgroundImages(GetBackgroundImageRequest) returns (GetBackgroundImagesResponse){
        option (google.api.http) = {
            get: "/v2/chat/background"
        };
    };
    rpc UpdateBackgroundImage(UpdateBackgroundImageRequest) returns (UpdateBackgroundImageResponse){
        option (google.api.http) = {
            put: "/v2/chat/background/{id}"
            body: "*"
        };
    };
    rpc DeleteBackgroundImage(DeleteBackgroundImageRequest) returns (DeleteBackgroundImageResponse){
        option (google.api.http) = {
            delete: "/v2/chat/background/delete/{id}"
        };
    };
}


message CreateBackgroundImageRequest {
    string imageUrl = 1;  
    string title = 2;      
    ImageType imageType = 3;  
    string description = 4;  
    string background = 5;
    string text = 6;
    string tint = 7;
}


message CreateBackgroundImageResponse {
    BackgroundImage backgroundImage = 1;  
}


message GetBackgroundImageRequest {
   optional int64 page = 1;
   optional int64 size = 2;  
}


message GetBackgroundImagesResponse {
    repeated BackgroundImage data = 1;  
    uint64 total = 2;
}


message UpdateBackgroundImageRequest {
    uint64 id = 1;  
    string imageUrl = 2;  
    string title = 3;      
    ImageType imageType = 4;  
    string description = 5;  
    string background = 6;
    string text = 7;
    string tint = 8;
}


message UpdateBackgroundImageResponse {
    BackgroundImage background_image = 1;  
}


message DeleteBackgroundImageRequest {
    uint64 id = 1;  
}


message DeleteBackgroundImageResponse {
    bool success = 1;  
}


message BackgroundImage {
    uint64 id = 1;  
    string imageUrl = 2;  
    string title = 3;  
    ImageType imageType = 4;  
    string description = 5;  
    string createdAt = 6;  
    string updatedAt = 7;  
    string color = 8;
    string background = 9;
    string text = 10;
    string tint = 11;
}


