syntax = "proto3";

package crmpb;

option go_package = "pb/types/crm;crmpb";

import "shared/common.proto";
import "google/api/annotations.proto";

service BlockService {
    rpc ListBlockedUsers(sharepb.IdRequest) returns (ListBlockResponse) {
        option (google.api.http) = {
            get: "/v2/crm/block/list"
        };
    };
    rpc BlockUser(BlockUserRequest) returns (sharepb.SubmitResponse) {
        option (google.api.http) = {
            post: "/v2/crm/block/{profileId}"
        };
    };
    rpc UnblockUser(sharepb.IdRequest) returns (sharepb.SubmitResponse) {
        option (google.api.http) = {
            delete: "/v2/crm/block/{id}"
        };
    };
}


message ListBlockResponse {
    repeated uint64 data = 1;
    int32 total = 2;
}

message BlockUserRequest {
    uint64 profileId = 1;
}