syntax = "proto3";

package crmpb;

option go_package = "pb/types/crm;crmpb";
import "google/api/annotations.proto";
import "shared/common.proto";

service TagService {
  rpc AdminCreateTag (AdminTagRequest) returns (TagItem) {
    option (google.api.http) = {
      post: "/v2/crm/tag/admin"
      body: "*"
    };
  };
  rpc AdminUpdateTag (AdminTagRequest) returns (TagItem) {
    option (google.api.http) = {
      put: "/v2/crm/tag/admin/{id}"
      body: "*"
    };
  };
  rpc AdminDeleteTag (sharepb.IdRequest) returns (sharepb.Empty) {
    option (google.api.http) = {
      delete: "/v2/crm/tag/admin/{id}"
    };
  };
  rpc ListTagsForContact (TagListRequest) returns (TagListResponse) {
    option (google.api.http) = {
      get: "/v2/crm/tag/list"
    };
  };
  rpc AdminListTags (AdminTagListRequest) returns (TagListResponse) {
    option (google.api.http) = {
      get: "/v2/crm/tag/admin/list"
    };
  };
  rpc ListTagsByContactID (sharepb.IdRequest) returns (TagListResponse) {
    option (google.api.http) = {
      get: "/v2/crm/tag/contact/{id}"
    };
  };
}

message AdminTagRequest {
  uint64 id = 1;
  string name = 2;
  bool isActive = 3;
  bool isDefault = 4;
}

message TagListRequest {
  uint32 page = 1;
  uint32 size = 2;
  string text = 3;
}

message AdminTagListRequest {
  uint32 page = 1;
  uint32 size = 2;
  string text = 3;
}

message TagItem {
  uint64 id = 1;
  string name = 2;
  bool isDefault = 3;
  bool isActive = 4;
  optional uint64 ownerId = 5;
  optional int32 ownerOf = 6;
  string createdAt = 7;
  string updatedAt = 8;
}

message TagListResponse {
  repeated TagItem data = 1;
  uint32 total = 2;
}

