package env

type DBType string

var (
	USER_CONTEXT             = "user_id"
	ADMIN_ROLE_KEY           = "admin"
	ADMIN_ROLE_NAME          = "Admin"
	MAX_ORGANIZATION_MEMBERS = 100

	// Organization Log Types
	LOG_TYPE_ORGANIZATION_CREATE = "ORGANIZATION_CREATE"
	LOG_TYPE_ORGANIZATION_UPDATE = "ORGANIZATION_UPDATE"
	LOG_TYPE_MEMBER_CREATE       = "MEMBER_CREATE"
	LOG_TYPE_MEMBER_UPDATE       = "MEMBER_UPDATE"
	LOG_TYPE_MEMBER_DELETE       = "MEMBER_DELETE"
	LOG_TYPE_ROLE_CREATE         = "ROLE_CREATE"
	LOG_TYPE_ROLE_UPDATE         = "ROLE_UPDATE"
	LOG_TYPE_ROLE_DELETE         = "ROLE_DELETE"
	LOG_TYPE_PERMISSION_CREATE   = "PERMISSION_CREATE"
	LOG_TYPE_PERMISSION_UPDATE   = "PERMISSION_UPDATE"
	LOG_TYPE_PERMISSION_DELETE   = "PERMISSION_DELETE"
	SERVICE_NAME                 = "organization-service"
	USER_SERVICE_ID              = "user-service"

	DBTypePostgres DBType = "postgres"

	DefaultDBDNS    = "host=localhost user=postgres password=postgres dbname=organization port=5432 sslmode=disable"
	DefaultGRPCPort = "8207"
)

var (
	GRPC_PORT                    = "8207"
	LOG_WORKER_QUEUE_SIZE        = 1000
	PRIMARY_DB_TYPE       DBType = ""
	DB_DNS                       = ""

	CHAT_SERVICE_HOST = "localhost"
	CHAT_SERVICE_PORT = "8208"

	USER_SERVICE_HOST = "localhost"
	USER_SERVICE_PORT = "8201"
)

var (
	CREATE_DEAL_PERMISSION                            = "CREATE_DEAL"
	UPDATE_DEAL_PERMISSION                            = "UPDATE_DEAL"
	CREATE_ORGANIZATION_BRANCH_PERMISSION             = "CREATE_ORGANIZATION_BRANCH"
	UPDATE_ORGANIZATION_BRANCH_PERMISSION             = "UPDATE_ORGANIZATION_BRANCH"
	DELETE_ORGANIZATION_BRANCH_PERMISSION             = "DELETE_ORGANIZATION_BRANCH"
	GET_ORGANIZATION_BRANCH_PERMISSION                = "GET_ORGANIZATION_BRANCH"
	ADD_MEMBER_TO_ORGANIZATION_BRANCH_PERMISSION      = "ADD_MEMBER_TO_ORGANIZATION_BRANCH"
	REMOVE_MEMBER_FROM_ORGANIZATION_BRANCH_PERMISSION = "REMOVE_MEMBER_FROM_ORGANIZATION_BRANCH"
	GET_ORGANIZATION_BRANCH_MEMBERS_PERMISSION        = "GET_ORGANIZATION_BRANCH_MEMBERS"
	UPDATE_IS_ACTIVE_ORGANIZATION_BRANCH_PERMISSION   = "UPDATE_IS_ACTIVE_ORGANIZATION_BRANCH"
	CREATE_ORGANIZATION_MEMBER_PERMISSION             = "CREATE_ORGANIZATION_MEMBER"
	UPDATE_ORGANIZATION_MEMBER_PERMISSION             = "UPDATE_ORGANIZATION_MEMBER"
	DELETE_ORGANIZATION_MEMBER_PERMISSION             = "DELETE_ORGANIZATION_MEMBER"
	GET_ORGANIZATION_MEMBERS_PERMISSION               = "GET_ORGANIZATION_MEMBERS"
	GET_CURRENT_ORGANIZATION_MEMBER_PERMISSION        = "GET_CURRENT_ORGANIZATION_MEMBER"
	GET_CURRENT_ORGANIZATION_MEMBER_ROLE_PERMISSION   = "GET_CURRENT_ORGANIZATION_MEMBER_ROLE"
	CHECK_USERS_IN_ORGANIZATION_PERMISSION            = "CHECK_USERS_IN_ORGANIZATION"
	CREATE_ORGANIZATION_PERMISSION                    = "CREATE_ORGANIZATION"
	UPDATE_ORGANIZATION_PERMISSION                    = "UPDATE_ORGANIZATION"
	DELETE_ORGANIZATION_PERMISSION                    = "DELETE_ORGANIZATION"
	GET_ORGANIZATION_PERMISSION                       = "GET_ORGANIZATION"
	CREATE_ORGANIZATION_ROLE_PERMISSION               = "CREATE_ORGANIZATION_ROLE"
	UPDATE_ORGANIZATION_ROLE_PERMISSION               = "UPDATE_ORGANIZATION_ROLE"
	DELETE_ORGANIZATION_ROLE_PERMISSION               = "DELETE_ORGANIZATION_ROLE"
	GET_ORGANIZATION_ROLES_PERMISSION                 = "GET_ORGANIZATION_ROLES"
	GET_ORGANIZATION_ROLE_PERMISSION                  = "GET_ORGANIZATION_ROLE"
	ADD_PERMISSION_TO_ORGANIZATION_ROLE_PERMISSION    = "ADD_PERMISSION_TO_ORGANIZATION_ROLE"
	CREATE_ORGANIZATION_ROLE_WITH_MEMBERS_PERMISSION  = "CREATE_ORGANIZATION_ROLE_WITH_MEMBERS"
	CHECKOUT_ORGANIZATION_SUBSCRIPTION_PERMISSION     = "CHECKOUT_ORGANIZATION_SUBSCRIPTION"
)
