// Package social Code generated by swaggo/swag. DO NOT EDIT
package social

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "parameters": [
                    {
                        "description": "CommentRequest",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentResponse"
                        }
                    }
                }
            }
        },
        "/comment/list/{newsFeedId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "mediaType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "mediaUrl",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "newsFeedId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentListResponse"
                        }
                    }
                }
            }
        },
        "/comment/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "parameters": [
                    {
                        "description": "CommentRequest",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "mediaType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "mediaUrl",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "newsFeedId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.CommentResponse"
                        }
                    }
                }
            }
        },
        "/like/comment/list/{commentId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CommentId",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListLikeResponse"
                        }
                    }
                }
            }
        },
        "/like/comment/{commentId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CommentId",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "LikeCommentRequest",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.LikeCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.LikeResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CommentId",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.LikeResponse"
                        }
                    }
                }
            }
        },
        "/like/news-feed/list/{newsFeedId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListLikeResponse"
                        }
                    }
                }
            }
        },
        "/like/news-feed/{newsFeedId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.LikeResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.LikeResponse"
                        }
                    }
                }
            }
        },
        "/news-feed": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Create a new news feed",
                "parameters": [
                    {
                        "description": "NewsFeed",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/detail/{newsFeedId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get news feed by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Lấy chi tiết news feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/global": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get global news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Lấy danh sách news feed",
                "parameters": [
                    {
                        "type": "boolean",
                        "name": "isPost",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "isReel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "OwnerOf_unknown",
                            "OwnerOf_user",
                            "OwnerOf_group",
                            "OwnerOf_organization"
                        ],
                        "name": "ownerOf",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListNewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/global/reel": {
            "get": {
                "description": "Get news feed by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Get news feed by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/global/{ownerOf}/{ownerId}": {
            "get": {
                "description": "Get global news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Lấy danh sách news feed",
                "parameters": [
                    {
                        "type": "boolean",
                        "name": "isPost",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "isReel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "OwnerOf_unknown",
                            "OwnerOf_user",
                            "OwnerOf_group",
                            "OwnerOf_organization"
                        ],
                        "name": "ownerOf",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListNewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/group": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new group news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Create a new news feed",
                "parameters": [
                    {
                        "description": "NewsFeed",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/user/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get news feed by userID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Lấy danh sách news feed theo userID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "name": "isPost",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "isReel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "OwnerOf_unknown",
                            "OwnerOf_user",
                            "OwnerOf_group",
                            "OwnerOf_organization"
                        ],
                        "name": "ownerOf",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListNewsFeed"
                        }
                    }
                }
            }
        },
        "/news-feed/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Update news feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "NewsFeed",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.NewsFeed"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xóa news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Xóa news feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/news-feed/{newsFeedId}/share": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Share news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Share news feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ShareRequest",
                        "name": "shareRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.ShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ShareResponse"
                        }
                    }
                }
            }
        },
        "/news-feed/{newsFeedId}/visibility": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update visibility of news feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Update visibility of news feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NewsFeedId",
                        "name": "newsFeedId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "VisibilityRequest",
                        "name": "visibility",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.VisibilityRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/news-feed/{ownerOf}/{ownerId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get news feed by owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News Feed"
                ],
                "summary": "Get news feed by owner",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OwnerOf",
                        "name": "ownerOf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "OwnerId",
                        "name": "ownerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "name": "isPost",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "isReel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "OwnerOf_unknown",
                            "OwnerOf_user",
                            "OwnerOf_group",
                            "OwnerOf_organization"
                        ],
                        "name": "ownerOf",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ListNewsFeed"
                        }
                    }
                }
            }
        },
        "/report/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách báo cáo của tôi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Lấy danh sách báo cáo của tôi",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "message",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ReportMessageResponse"
                        }
                    }
                }
            }
        },
        "/report/reasons": {
            "get": {
                "description": "Danh sách lý do báo cáo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Danh sách lý do báo cáo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ReportReasonResponse"
                        }
                    }
                }
            }
        },
        "/report/status/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật trạng thái báo cáo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Cập nhật trạng thái báo cáo",
                "parameters": [
                    {
                        "description": "ReportStatusRequest",
                        "name": "report",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.ReportStatusRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/report/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gửi báo cáo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Gửi báo cáo",
                "parameters": [
                    {
                        "description": "ReportRequest",
                        "name": "report",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb_social.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb_social.ReportResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bdspropb.Post": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "districtName": {
                    "type": "string"
                },
                "expiredAt": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "like": {
                    "type": "integer"
                },
                "mediaList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bdspropb.PostMedia"
                    }
                },
                "mediaType": {
                    "type": "string"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "numDate": {
                    "type": "integer"
                },
                "numView": {
                    "type": "integer"
                },
                "ownerId": {
                    "type": "integer"
                },
                "ownerType": {
                    "description": "1: user, 2: admin",
                    "type": "integer"
                },
                "packageVisible": {
                    "description": "1: thường, 2: VIP",
                    "type": "integer"
                },
                "postPrice": {
                    "type": "number"
                },
                "priceType": {
                    "description": "1: chính thức, 2: thỏa thuận",
                    "type": "integer"
                },
                "productId": {
                    "type": "integer"
                },
                "provinceName": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "transactionType": {
                    "type": "integer"
                },
                "type": {
                    "description": "1: normal, 2: feed, 3: share",
                    "type": "string"
                },
                "visibility": {
                    "type": "integer"
                },
                "wardName": {
                    "type": "string"
                }
            }
        },
        "bdspropb.PostMedia": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isMain": {
                    "type": "boolean"
                },
                "mediaType": {
                    "type": "string"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                }
            }
        },
        "pb_social.CommentListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.CommentResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pb_social.CommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mediaType": {
                    "type": "string"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "newsFeedId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "parentId": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "pb_social.CommentResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/sharepb.ProfileItem"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "dislike": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "likedAt": {
                    "type": "string"
                },
                "mediaType": {
                    "type": "string"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "newsFeedId": {
                    "type": "integer"
                },
                "numDisLike": {
                    "type": "integer"
                },
                "numLike": {
                    "type": "integer"
                },
                "numReply": {
                    "type": "integer"
                },
                "parentId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "pb_social.LikeCommentRequest": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "integer"
                },
                "dislike": {
                    "type": "boolean"
                }
            }
        },
        "pb_social.LikeResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                },
                "targetType": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ListLikeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.LikeResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ListNewsFeed": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.NewsFeed"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pb_social.NewsFeed": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/sharepb.ProfileItem"
                },
                "content": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "disLike": {
                    "type": "boolean"
                },
                "friendTagIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "friendTags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharepb.ProfileItem"
                    }
                },
                "groupId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "isReel": {
                    "type": "boolean"
                },
                "likedAt": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "mediaFeeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.NewsFeedMedia"
                    }
                },
                "numComment": {
                    "type": "integer"
                },
                "numLike": {
                    "type": "integer"
                },
                "numShare": {
                    "type": "integer"
                },
                "numView": {
                    "type": "integer"
                },
                "ownerOf": {
                    "$ref": "#/definitions/pb_social.OwnerOf"
                },
                "post": {
                    "$ref": "#/definitions/bdspropb.Post"
                },
                "postId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "visibility": {
                    "type": "integer"
                }
            }
        },
        "pb_social.NewsFeedMedia": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "orderNumber": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pb_social.OwnerOf": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "OwnerOf_unknown",
                "OwnerOf_user",
                "OwnerOf_group",
                "OwnerOf_organization"
            ]
        },
        "pb_social.ReportMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reasonId": {
                    "type": "integer"
                },
                "reasonName": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "statusName": {
                    "type": "string"
                },
                "targetId": {
                    "type": "integer"
                },
                "targetName": {
                    "type": "string"
                },
                "targetType": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ReportMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.ReportMessage"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ReportReason": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "reasonName": {
                    "type": "string"
                }
            }
        },
        "pb_social.ReportReasonResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb_social.ReportReason"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ReportRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reasonId": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                },
                "targetType": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ReportResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reasonId": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                },
                "targetType": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ReportStatusRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ShareRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "newsFeedId": {
                    "type": "integer"
                },
                "shareType": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                }
            }
        },
        "pb_social.ShareResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "pb_social.VisibilityRequest": {
            "type": "object",
            "properties": {
                "newsFeedId": {
                    "type": "integer"
                },
                "visibility": {
                    "type": "integer"
                }
            }
        },
        "sharepb.ProfileItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isMember": {
                    "type": "boolean"
                },
                "joinedAt": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "tickVerified": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2/social",
	Schemes:          []string{},
	Title:            "Social Service",
	Description:      "Social Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
