// Package assistant Code generated by swaggo/swag. DO NOT EDIT
package assistant

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v2/assistant/bdspro/product": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sử dụng AI để phân tích và trích xuất thông tin từ văn bản mô tả sản phẩm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Phân tích văn bản sản phẩm BĐS sử dụng AI",
                "parameters": [
                    {
                        "description": "Nội dung cần phân tích",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.SuggestResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thực hiện conversation với AI assistant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Chat với AI assistant",
                "parameters": [
                    {
                        "description": "Message và history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/deepseek/analyze/product": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sử dụng DeepSeek AI để phân tích và trích xuất thông tin từ văn bản mô tả sản phẩm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Phân tích văn bản sản phẩm BĐS sử dụng DeepSeek AI",
                "parameters": [
                    {
                        "description": "Nội dung cần phân tích",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/deepseek/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thực hiện conversation với DeepSeek AI assistant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Chat với DeepSeek AI assistant",
                "parameters": [
                    {
                        "description": "Message và history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/deepseek/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo nội dung theo template và prompt sử dụng DeepSeek",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Generate nội dung với DeepSeek",
                "parameters": [
                    {
                        "description": "Prompt và template",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/gemini/analyze/product": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sử dụng Google Gemini AI để phân tích và trích xuất thông tin từ văn bản mô tả sản phẩm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Phân tích văn bản sản phẩm BĐS sử dụng Gemini AI",
                "parameters": [
                    {
                        "description": "Nội dung cần phân tích",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/gemini/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thực hiện conversation với Google Gemini AI assistant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Chat với Gemini AI assistant",
                "parameters": [
                    {
                        "description": "Message và history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/gemini/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo nội dung theo template và prompt sử dụng Google Gemini",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Generate nội dung với Gemini",
                "parameters": [
                    {
                        "description": "Prompt và template",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo nội dung theo template và prompt",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Generate nội dung",
                "parameters": [
                    {
                        "description": "Prompt và template",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/health": {
            "get": {
                "description": "Kiểm tra trạng thái service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/national-card/extract": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Nhận vào 2 link ảnh (mặt trước và mặt sau), sử dụng OCR để đọc thông tin và MRZ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Trích xuất thông tin từ ảnh căn cước công dân",
                "parameters": [
                    {
                        "description": "Link ảnh căn cước",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ExtractNationalCardRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thông tin đã trích xuất",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ExtractNationalCardResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/assistant/openai/analyze/product": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sử dụng OpenAI GPT để phân tích và trích xuất thông tin từ văn bản mô tả sản phẩm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Phân tích văn bản sản phẩm BĐS sử dụng OpenAI",
                "parameters": [
                    {
                        "description": "Nội dung cần phân tích",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.AnalyzeResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/openai/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thực hiện conversation với OpenAI GPT assistant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Chat với OpenAI AI assistant",
                "parameters": [
                    {
                        "description": "Message và history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.ChatResponse"
                        }
                    }
                }
            }
        },
        "/v2/assistant/openai/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo nội dung theo template và prompt sử dụng OpenAI GPT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assistant"
                ],
                "summary": "Generate nội dung với OpenAI",
                "parameters": [
                    {
                        "description": "Prompt và template",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/assistantpb.GenerateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "assistantpb.AnalysisMetadata": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "model": {
                    "type": "string"
                },
                "processing_time_ms": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                }
            }
        },
        "assistantpb.AnalyzeRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Văn bản mô tả sản phẩm cần phân tích",
                    "type": "string"
                },
                "context": {
                    "description": "Context bổ sung (optional)",
                    "type": "string"
                }
            }
        },
        "assistantpb.AnalyzeResponse": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/assistantpb.AnalysisMetadata"
                },
                "product": {
                    "$ref": "#/definitions/assistantpb.ProductInfo"
                },
                "raw_response": {
                    "description": "Raw JSON từ AI",
                    "type": "string"
                }
            }
        },
        "assistantpb.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "description": "\"user\" hoặc \"assistant\"",
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "assistantpb.ChatMetadata": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "processing_time_ms": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                }
            }
        },
        "assistantpb.ChatRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "Context bổ sung",
                    "type": "string"
                },
                "history": {
                    "description": "Chat history",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/assistantpb.ChatMessage"
                    }
                },
                "message": {
                    "type": "string"
                },
                "session_id": {
                    "description": "Session ID để maintain conversation",
                    "type": "string"
                }
            }
        },
        "assistantpb.ChatResponse": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/assistantpb.ChatMetadata"
                },
                "reply": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "assistantpb.ExtractMetadata": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "description": "Độ tin cậy (0-1)",
                    "type": "number"
                },
                "model": {
                    "type": "string"
                },
                "processing_time_ms": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                }
            }
        },
        "assistantpb.ExtractNationalCardRequest": {
            "type": "object",
            "properties": {
                "backImageUrl": {
                    "description": "Link ảnh mặt sau căn cước",
                    "type": "string"
                },
                "frontImageUrl": {
                    "description": "Link ảnh mặt trước căn cước",
                    "type": "string"
                }
            }
        },
        "assistantpb.ExtractNationalCardResponse": {
            "type": "object",
            "properties": {
                "info": {
                    "$ref": "#/definitions/assistantpb.NationalCardInfo"
                },
                "metadata": {
                    "$ref": "#/definitions/assistantpb.ExtractMetadata"
                },
                "mrz": {
                    "description": "Machine Readable Zone (MRZ) nếu có",
                    "type": "string"
                }
            }
        },
        "assistantpb.GenerateMetadata": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "processing_time_ms": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                }
            }
        },
        "assistantpb.GenerateRequest": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "temperature": {
                    "description": "0.0 - 1.0",
                    "type": "number"
                },
                "template": {
                    "description": "Template type: \"product_description\", \"email\", \"social_post\"",
                    "type": "string"
                },
                "variables": {
                    "description": "Variables để thay vào template",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "assistantpb.GenerateResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/assistantpb.GenerateMetadata"
                }
            }
        },
        "assistantpb.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "description": "Component health checks",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "\"healthy\", \"degraded\", \"unhealthy\"",
                    "type": "string"
                },
                "uptime_seconds": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "assistantpb.NationalCardInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Địa chỉ",
                    "type": "string"
                },
                "dateOfBirth": {
                    "description": "Ngày sinh (dd/mm/yyyy)",
                    "type": "string"
                },
                "ethnic": {
                    "description": "Dân tộc",
                    "type": "string"
                },
                "expiryDate": {
                    "description": "Ngày hết hạn (nếu có)",
                    "type": "string"
                },
                "features": {
                    "description": "Đặc điểm nhận dạng",
                    "type": "string"
                },
                "fullName": {
                    "description": "Họ và tên",
                    "type": "string"
                },
                "gender": {
                    "description": "Giới tính",
                    "type": "string"
                },
                "idNumber": {
                    "description": "Thông tin từ mặt trước",
                    "type": "string"
                },
                "issueDate": {
                    "description": "Thông tin từ mặt sau",
                    "type": "string"
                },
                "issuePlace": {
                    "description": "Nơi cấp",
                    "type": "string"
                },
                "nationality": {
                    "description": "Quốc tịch",
                    "type": "string"
                },
                "placeOfOrigin": {
                    "description": "Quê quán",
                    "type": "string"
                },
                "placeOfResidence": {
                    "description": "Nơi thường trú",
                    "type": "string"
                },
                "religion": {
                    "description": "Tôn giáo",
                    "type": "string"
                }
            }
        },
        "assistantpb.ProductInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amenities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "area": {
                    "type": "number"
                },
                "bathroom": {
                    "type": "integer"
                },
                "bedroom": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "floor": {
                    "type": "integer"
                },
                "frontage": {
                    "type": "number"
                },
                "furniture": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "legalDoc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orientation": {
                    "type": "string"
                },
                "propertyType": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "rent_price": {
                    "type": "number"
                },
                "salePrice": {
                    "type": "number"
                },
                "transaction_type": {
                    "description": "1=Bán, 2=Thuê, 3=Cả hai",
                    "type": "integer"
                },
                "ward": {
                    "type": "string"
                }
            }
        },
        "assistantpb.SuggestResponse": {
            "type": "object",
            "properties": {
                "modelName": {
                    "type": "string"
                },
                "processingTime": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/sharepb.ProductV3Proto"
                }
            }
        },
        "sharepb.AddressV3Proto": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "districtId": {
                    "type": "integer"
                },
                "districtName": {
                    "type": "string"
                },
                "provinceId": {
                    "type": "integer"
                },
                "provinceName": {
                    "type": "string"
                },
                "wardId": {
                    "type": "integer"
                },
                "wardName": {
                    "type": "string"
                }
            }
        },
        "sharepb.HouseInfoV3Proto": {
            "type": "object",
            "properties": {
                "furniture": {
                    "type": "string"
                },
                "numBathroom": {
                    "type": "integer"
                },
                "numBedroom": {
                    "type": "integer"
                },
                "numCarPark": {
                    "type": "integer"
                },
                "numFloor": {
                    "type": "integer"
                },
                "numFront": {
                    "type": "number"
                },
                "orientation": {
                    "type": "string"
                }
            }
        },
        "sharepb.ItemV3Proto": {
            "type": "object",
            "properties": {
                "fileName": {
                    "description": "file upload",
                    "type": "string"
                },
                "fileType": {
                    "type": "string"
                },
                "fileUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "issuedAt": {
                    "type": "string"
                },
                "issuer": {
                    "type": "integer"
                },
                "itemType": {
                    "description": "tag",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "approved",
                    "type": "integer"
                }
            }
        },
        "sharepb.PriceV3Proto": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "rentCommission": {
                    "type": "number"
                },
                "rentCommissionType": {
                    "type": "integer"
                },
                "rentPaymentCycle": {
                    "type": "integer"
                },
                "rentPrice": {
                    "type": "number"
                },
                "saleCommission": {
                    "type": "number"
                },
                "saleCommissionType": {
                    "type": "integer"
                },
                "salePrice": {
                    "type": "number"
                }
            }
        },
        "sharepb.ProductV3Proto": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/sharepb.AddressV3Proto"
                },
                "amenities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharepb.ItemV3Proto"
                    }
                },
                "area": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "docType": {
                    "$ref": "#/definitions/sharepb.ItemV3Proto"
                },
                "houseInfo": {
                    "$ref": "#/definitions/sharepb.HouseInfoV3Proto"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priceData": {
                    "$ref": "#/definitions/sharepb.PriceV3Proto"
                },
                "propertyType": {
                    "$ref": "#/definitions/sharepb.ItemV3Proto"
                },
                "sourceType": {
                    "$ref": "#/definitions/sharepb.ItemV3Proto"
                },
                "transactionType": {
                    "$ref": "#/definitions/sharepb.ItemV3Proto"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Assistant API",
	Description:      "API cho assistant service, bao gồm event-queue và các tiện ích khác",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
