syntax = "proto3";

package bdspropb;
option go_package = "pb/types/bdspro;bdspropb";
import "google/protobuf/timestamp.proto";
import "bdspro/common.proto";
import "google/api/annotations.proto";
import "shared/common.proto";

service AssetService {
  rpc SearchInternal(AssetSearchRequest) returns (AssetSearchResponse) {
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/internal"
    };
  };
  rpc SearchShare(AssetSearchRequest) returns (AssetSearchResponse) {
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/search-share"
    };
  };
  rpc SearchSplit(AssetSearchRequest) returns (AssetSearchResponse) {
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/split"
    };
  };
  rpc Archived(ArchivedRequest) returns (Response) {
    option (google.api.http) = {
      put: "/v2/bdspro/v2/asset/archived"
    };
  };
  rpc CreateAsset(SaveAssetRequest) returns (Response){
    option (google.api.http) = {
      post: "/v2/bdspro/v2/asset"
      body: "*"
    };
  };
  rpc UpdateAsset(SaveAssetRequest) returns (Response) {
    option (google.api.http) = {
      put: "/v2/bdspro/v2/asset/{id}"
      body: "*"
    };
  };
  rpc DeleteAsset(IdRequest) returns (Response) {
    option (google.api.http) = {
      delete: "/v2/bdspro/v2/asset/{id}"
    };
  };
  rpc GetDetail(sharepb.IdRequest) returns (Asset){
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/detail/{id}"
    };
  };
  rpc Merge(MergeAssetRequest) returns (Asset) {
    option (google.api.http) = {
      post: "/v2/bdspro/v2/asset/merge"
      body: "*"
    };
  };
  rpc Split(SplitAssetRequest) returns (Asset) {
    option (google.api.http) = {
      post: "/v2/bdspro/v2/asset/split"
      body: "*"
    };
  };
  // rpc History(IdRequest) returns (HistoryResponse) {
  //   option (google.api.http) = {
  //     get: "/v2/bdspro/v2/asset/history/{id}"
  //   };
  // };
  // rpc HistoryOwner(IdRequest) returns (HistoryResponse) {
  //   option (google.api.http) = {
  //     get: "/v2/bdspro/v2/asset/history/owner"
  //   };
  // };
  rpc GetPublish(IdRequest) returns (AssetSearchResponse) {
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/publish/{id}" // profileId
    };
  };
  
  // Asset Management APIs for Organizations
  rpc CreateAssetOrganization (SaveAssetRequest) returns (Response) {
    option (google.api.http) = {
      post: "/v2/bdspro/v2/asset/organization"
      body: "*"
    };
  };
  rpc CurrentOrganizationAssets (AssetSearchRequest) returns (AssetSearchResponse) {
    option (google.api.http) = {
      get: "/v2/bdspro/v2/asset/organization"
    };
  };
}

message AssetList {
  repeated Asset data = 1;
}

message DeleteAssetRequest {
  uint64 id = 1;
}

// message CreateAssetRequest {
//   uint64 id = 1;
//   string name = 2;
//   uint64 wardId = 3;
//   uint64 districtId = 4;
//   uint64 provinceId = 5;
//   double price = 6;
//   uint64 docStatus = 7; // 1: sổ đỏ, 2: sổ hồng, 3: chưa có sổ
//   optional uint64 productId = 8;
//   optional uint64 ownerUserId = 9;
//   optional uint64 ownerOrgId = 10;
//   optional uint64 parentAssetId = 11;
//   string splitMergeStatus = 12;
//   double purchasePrice = 13;
//   string purchaseDate = 14;
//   bool archived = 15;
//   uint32 rentStatus = 16;
//   double area = 17;
//   string address = 18;
//   string description = 19;
//   optional uint64 propertyTypeId = 20;
// }

message SaveAssetRequest {
  uint64 id = 1;
  string name = 2;
  double area = 3;
  optional uint64 wardId = 4;
  optional uint64 districtId = 5;
  optional uint64 provinceId = 6;
  optional uint64 productId = 7;
  optional uint64 parentAssetId = 8;
  string splitMergeStatus = 9;
  double purchasePrice = 10;
  string purchaseDate = 11;
  uint32 legalStatus = 12; // 10: sổ đỏ, 20: sổ hồng, 30: chưa có sổ
  bool archived = 13;
  uint32 rentStatus = 14;
  string address = 15;
  string description = 16;
  optional uint64 propertyTypeId = 18;
  repeated LegalItem legalItems = 19;
  uint32 ownerType = 20;
}


message BulkActionRequest {
  repeated uint64 ids = 1;
  uint32 action = 2;
}

message FilterAssetsRequest {
  string keyword = 1;
  uint32 type = 2;
  bool archived = 3;
}

message AssetDetails {
  Asset data = 1;
}

message ShareAssetRequest {
  uint64 id = 1;
  repeated string user_ids = 2;
}

message SplitAssetRequest {
  uint64 id = 1;
  repeated Asset datas = 2;
}

message MergeAssetRequest {
  repeated uint64 ids = 1;
  string new_name = 2;
  uint64 id = 3;
}

message AssetHistory {
  uint64 asset_id = 1;
  repeated string changes = 2;
}


// Use Case 1: Tạo mới hoàn toàn (không có sản phẩm)
message CreateAssetRequestNew {
  string name = 1;
  double area = 2;
  string address = 3;
  string description = 4;
  google.protobuf.Timestamp purchase_date = 5;
  double purchase_price = 6;
}

// Use Case 2: Tạo từ sản phẩm có sẵn
message CreateAssetRequestFromProduct {
  uint64 product_id = 1;
  string name = 2;
  string description = 3;
  google.protobuf.Timestamp purchase_date = 4;
  double purchase_price = 5;
}

// Use Case 3: Chuyển sản phẩm thành tài sản
message CreateAssetRequestConvertProduct {
  uint64 product_id = 1;
  string name = 2;
  string address = 3;
  double area = 4;
  string description = 5;
  google.protobuf.Timestamp purchase_date = 6;
  double purchase_price = 7;
}

message AssetSearchRequest {
  string keyword = 1;
  uint32 type = 2;
  bool archived = 3;
}

message AssetSearchResponse {
  repeated Asset data = 1;
  uint64 total = 2;
}
