// Package tqd Code generated by swaggo/swag. DO NOT EDIT
package tqd

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contact/labels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List contact labels with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "List contact labels with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is active",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is system",
                        "name": "isSystem",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List contact labels response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListContactLabelsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Create a new contact label",
                "parameters": [
                    {
                        "description": "Contact label",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            }
        },
        "/contact/labels/{id}": {
            "get": {
                "description": "Get a contact label by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Get a contact label by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Update a contact label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contact label",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Delete a contact label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        },
        "/service/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List service categories with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "List service categories with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is active",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Level",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Create a new service category",
                "parameters": [
                    {
                        "description": "Service category",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Service category",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                }
            }
        },
        "/service/categories/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get active service categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get active service categories",
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            }
        },
        "/service/categories/level/{level}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get service categories by level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get service categories by level",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Level",
                        "name": "level",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            }
        },
        "/service/categories/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a service category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get a service category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Service category",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Update a service category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service category",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Service category",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Delete a service category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/contact/labels": {
            "get": {
                "description": "List contact labels with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "List contact labels with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is active",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is system",
                        "name": "isSystem",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List contact labels response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListContactLabelsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Create a new contact label",
                "parameters": [
                    {
                        "description": "Contact label",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            }
        },
        "/v2/tqd/contact/labels/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a contact label by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Get a contact label by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Update a contact label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contact label",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contact label",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ContactLabel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a contact label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact Label"
                ],
                "summary": "Delete a contact label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact label ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories": {
            "get": {
                "description": "List service categories with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "List service categories with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is active",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Level",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Create a new service category",
                "parameters": [
                    {
                        "description": "Service category",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/infra.Response"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/active": {
            "get": {
                "description": "Get active service categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get active service categories",
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/bulk": {
            "put": {
                "description": "Bulk update service categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Bulk update service categories",
                "parameters": [
                    {
                        "description": "Service categories",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tqdpb.DirectoryCategory"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/code/{code}": {
            "get": {
                "description": "Get service category by code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get service category by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/infra.Response"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/level/{level}": {
            "get": {
                "description": "Get service categories by level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get service categories by level",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Level",
                        "name": "level",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List service categories response",
                        "schema": {
                            "$ref": "#/definitions/tqdpb.ListServiceCategoriesResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/stats": {
            "get": {
                "description": "Get service categories statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get service categories statistics",
                "responses": {
                    "200": {
                        "description": "Statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/{id}": {
            "get": {
                "description": "Get a service category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Get a service category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/infra.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Update a service category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service category",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tqdpb.DirectoryCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/infra.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a service category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Delete a service category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        },
        "/v2/tqd/service/categories/{id}/count": {
            "put": {
                "description": "Update service count for a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Category"
                ],
                "summary": "Update service count for a category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service count",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit response",
                        "schema": {
                            "$ref": "#/definitions/sharepb.SubmitResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "infra.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "totalElement": {
                    "type": "integer"
                }
            }
        },
        "sharepb.SubmitResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "tqdpb.ContactLabel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "contactCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isSystem": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "tqdpb.ListContactLabelsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tqdpb.ContactLabel"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "tqdpb.ListServiceCategoriesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tqdpb.DirectoryCategory"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "tqdpb.DirectoryCategory": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "serviceCount": {
                    "type": "integer"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2/tqd",
	Schemes:          []string{},
	Title:            "TQD API",
	Description:      "API phần logic chính của TQD. Đã chuyển sang grpc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
