// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"common/db"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"map/config"
	"map/infra/db"
	"map/infra/handler"
	"map/infra/postgre"
	"map/initial"
	"map/internal/usecase"
)

// Injectors from wire.go:

// InitializeApp khởi tạo toàn bộ hệ thống với Wire
func InitializeApp() (*gin.Engine, error) {
	db, err := _db.NewDB()
	if err != nil {
		return nil, err
	}
	mapPointRepository := postgre.NewMapPointPostgres(db)
	mapPointUsecase := usecase.NewMapPointUsecase(mapPointRepository)
	mapPointHandler := handler.NewMapPointHandler(mapPointUsecase)
	engine := NewRouter(mapPointHandler)
	return engine, nil
}

// wire.go:

// WireSet tập hợp các dependencies để inject
var WireSet = wire.NewSet(config.LoadConfig, _db.NewDB, db.Migrate, postgre.NewMapPointPostgres, usecase.NewMapPointUsecase, handler.NewMapPointHandler, NewRouter)

// InitializeRuntime khởi tạo runtime
func InitializeRuntime() error {
	return initial.InitializeRuntime()
}
