package gen_mapper

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

type MapperPair struct {
	From      reflect.Type
	To        reflect.Type
	FromAlias string
	ToAlias   string
	ToPkgPath string
	FuncName  string
}

func GenerateMapper(mappers []MapperPair) {
	var out strings.Builder
	out.WriteString(`// Code generated by gen_mapper; DO NOT EDIT.

package domain

import (
	pb "pb/types/auth"
)
`)

	for _, m := range mappers {
		genMapper(&out, m)
	}

	// ghi vào internal/domain/__gen__.go
	err := os.WriteFile("internal/domain/__gen__.go", []byte(out.String()), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Println("✅ Generated internal/domain/__gen__.go")
}

func genMapper(sb *strings.Builder, mp MapperPair) {
	// Lấy tên folder cuối cùng trong đường dẫn gói To
	folder := filepath.Base(mp.ToPkgPath)
	// Viết hoa chữ cái đầu để đặt tên method
	methodSuffix := strings.Title(folder)

	// Method được define trực tiếp trên type trong package domain
	fmt.Fprintf(sb, "func (o *%s) To%s() %s.%s {\n",
		mp.From.Name(),
		methodSuffix,
		mp.ToAlias, mp.To.Name(),
	)
	fmt.Fprintf(sb, "    return %s.%s{\n", mp.ToAlias, mp.To.Name())

	fromFields := make(map[string]reflect.StructField)
	for i := 0; i < mp.From.NumField(); i++ {
		f := mp.From.Field(i)
		fromFields[f.Name] = f
	}

	for i := 0; i < mp.To.NumField(); i++ {
		tf := mp.To.Field(i)
		if _, ok := fromFields[tf.Name]; ok {
			fmt.Fprintf(sb, "        %s: o.%s,\n", tf.Name, tf.Name)
		}
	}

	fmt.Fprintf(sb, "    }\n}\n\n")
}
