syntax = "proto3";

package bdspropb;
option go_package = "pb/types/bdspro;bdspropb";

message AssetSplitHistoryDTO {
  uint64 id = 1;
  bool archived = 2;
}

message AssetSplitHistoryListDTO {
  repeated AssetSplitHistoryDTO data = 1;
  uint32 totalElements = 2;
}

service AssetSplitHistoryService {
    rpc Get (AssetSplitHistoryDTO) returns (AssetSplitHistoryListDTO);
    rpc Detail (AssetSplitHistoryDTO) returns (AssetSplitHistoryDTO);
    rpc Create (AssetSplitHistoryDTO) returns (AssetSplitHistoryDTO);
    rpc Update (AssetSplitHistoryDTO) returns (AssetSplitHistoryDTO);
    rpc Delete (AssetSplitHistoryDTO) returns (AssetSplitHistoryDTO);
}
