syntax = "proto3";

package crmpb;

option go_package = "pb/types/crm;crmpb";
import "google/api/annotations.proto";
import "shared/common.proto";
import "crm/common.proto";

message StageSearchRequest {
    uint64 pipelineId = 1;
    uint32 page = 2;
    uint32 size = 3;
    string stageName = 4;
}

message StageListDTO {
    repeated StageDTO data = 1;
    uint32 total = 2;
}

service StageService {
    rpc Search (StageSearchRequest) returns (StageListDTO){
        option (google.api.http) = {
            get: "/v2/crm/stage/list/{pipelineId}"
        };
    };
    rpc Detail (StageDTO) returns (StageDTO) {
        option (google.api.http) = {
            get: "/v2/crm/stage/detail/{id}"
        };
    };
    rpc Create (StageDTO) returns (StageDTO) {
        option (google.api.http) = {
            post: "/v2/crm/stage"
            body: "*"
        };
    };
    rpc Update (StageDTO) returns (StageDTO) {
        option (google.api.http) = {
            put: "/v2/crm/stage/{id}"
            body: "*"
        };
    };
    rpc Delete (sharepb.IdRequest) returns (sharepb.SubmitResponse) {
        option (google.api.http) = {
            delete: "/v2/crm/stage/{id}"
        };
    };
}
