//go:build wireinject
// +build wireinject

package wire

import (
	bdspro_infra_client "bdspro/infra/client"
	bdspro_infra_handler "bdspro/infra/handler"
	bdspro_infra_handler_admin "bdspro/infra/handler/admin"
	bdspro_infra_handler_property "bdspro/infra/handler/property"
	bdspro_infra_mapper "bdspro/infra/mapper"
	bdspro_infra_postgre "bdspro/infra/postgre"
	bdspro_infra_postgres "bdspro/infra/postgres"
	bdspro_infra_postgres_admin "bdspro/infra/postgres/admin"
	bdspro_infra_postgres_audit "bdspro/infra/postgres/audit"
	bdspro_infra_providers "bdspro/infra/providers"
	bdspro_infra_redis "bdspro/infra/redis"
	bdspro_infra_router_org "bdspro/infra/router/org"
	bdspro_infra_router_public "bdspro/infra/router/public"
	bdspro_infra_router_user "bdspro/infra/router/user"
	bdspro_infra_rpc "bdspro/infra/rpc"
	bdspro_infra_validator "bdspro/infra/validator"
	bdspro_initial "bdspro/initial"
	bdspro_internal_job "bdspro/internal/job"
	bdspro_internal_modules "bdspro/internal/modules"
	bdspro_internal_provider "bdspro/internal/provider"
	bdspro_internal_repo "bdspro/internal/repo"
	bdspro_internal_repo_admin "bdspro/internal/repo/admin"
	bdspro_internal_usecases "bdspro/internal/usecases"
	bdspro_internal_usecases_admin "bdspro/internal/usecases/admin"
	bdspro_internal_usecases_property "bdspro/internal/usecases/property"
	bdspro_internal_usecases_shared "bdspro/internal/usecases/shared"
	_db "common/db"
	common_injection "common/injection"
	_provider "common/provider"
	common_utils "common/utils"
	"github.com/google/wire"
)

// Inject dependencies
var wireSet = wire.NewSet(
	_db.NewDB,
	_db.NewTransactionRepo,
	_provider.SyncProviderSet,
	wire.Bind(new(bdspro_internal_provider.DeepseekProvider), new(*bdspro_infra_client.DeepseekClient)),
	wire.Bind(new(bdspro_internal_provider.HubProvider), new(*bdspro_infra_client.HubClient)),
	wire.Bind(new(bdspro_internal_provider.IUserProvider), new(*bdspro_infra_client.UserClient)),
	wire.Bind(new(bdspro_internal_provider.PlanProvider), new(*bdspro_infra_providers.MemberPlanProvider)),
	wire.Bind(new(bdspro_internal_provider.TransactionProvider), new(*bdspro_infra_postgres.TransactionGorm)),
	wire.Bind(new(bdspro_internal_repo.ApartmentRepo), new(*bdspro_infra_postgres.PostgreApartment)),
	wire.Bind(new(bdspro_internal_repo.AssetCostRepo), new(*bdspro_infra_postgres.GormAssetCostRepo)),
	wire.Bind(new(bdspro_internal_repo.AssetCostTypeRepo), new(*bdspro_infra_postgres.PostgreUserCostType)),
	wire.Bind(new(bdspro_internal_repo.AssetExploitationRepo), new(*bdspro_infra_postgres.PostgreAssetExploitation)),
	wire.Bind(new(bdspro_internal_repo.AssetIncomeTypeRepo), new(*bdspro_infra_postgres.GormAssetIncomeTypeRepo)),
	wire.Bind(new(bdspro_internal_repo.AssetLegalRepo), new(*bdspro_infra_postgres.GormAssetLegalRepo)),
	wire.Bind(new(bdspro_internal_repo.AssetOrganizationRepo), new(*bdspro_infra_postgres.PostgreAssetOrganization)),
	wire.Bind(new(bdspro_internal_repo.AssetRepo), new(*bdspro_infra_postgres.PostgreAsset)),
	wire.Bind(new(bdspro_internal_repo.AssetShareRepo), new(*bdspro_infra_postgres.AssetShareRepo)),
	wire.Bind(new(bdspro_internal_repo.AssetUserRepo), new(*bdspro_infra_postgres.PostgreAssetUser)),
	wire.Bind(new(bdspro_internal_repo.BankAccountRepository), new(*bdspro_infra_postgres.BankAccountPostgresRepository)),
	wire.Bind(new(bdspro_internal_repo.BdsDomainRepo), new(*bdspro_infra_postgres.BdsDomainPostgres)),
	wire.Bind(new(bdspro_internal_repo.CostDocumentRepo), new(*bdspro_infra_postgres.GormCostDocumentRepo)),
	wire.Bind(new(bdspro_internal_repo.DealMemberRepository), new(*bdspro_infra_postgres.DealMemberPostgresRepository)),
	wire.Bind(new(bdspro_internal_repo.DealMilestoneRepository), new(*bdspro_infra_postgres.DealMilestonePostgresRepository)),
	wire.Bind(new(bdspro_internal_repo.DocTypeRepo), new(*bdspro_infra_postgres.PostgreDocType)),
	wire.Bind(new(bdspro_internal_repo.DocumentRepository), new(*bdspro_infra_postgres.DocumentPostgresRepository)),
	wire.Bind(new(bdspro_internal_repo.HouseInfoRepo), new(*bdspro_infra_postgres.GormHouseInfoRepo)),
	wire.Bind(new(bdspro_internal_repo.IncomeDocumentRepo), new(*bdspro_infra_postgres.GormIncomeDocumentRepo)),
	wire.Bind(new(bdspro_internal_repo.InvestmentRepository), new(*bdspro_infra_postgres.InvestmentPostgres)),
	wire.Bind(new(bdspro_internal_repo.PostMediaRepo), new(*bdspro_infra_postgres.GormPostMediaRepo)),
	wire.Bind(new(bdspro_internal_repo.PostOrganizationRepo), new(*bdspro_infra_postgres.PostgrePostOrganization)),
	wire.Bind(new(bdspro_internal_repo.PostRepo), new(*bdspro_infra_postgres.GormPostRepo)),
	wire.Bind(new(bdspro_internal_repo.PostUserRepo), new(*bdspro_infra_postgres.PostgrePostUser)),
	wire.Bind(new(bdspro_internal_repo.ProductAssetRepo), new(*bdspro_infra_postgres.ProductAssetPostgres)),
	wire.Bind(new(bdspro_internal_repo.ProductHistoryRepo), new(*bdspro_infra_postgres.PostgreHistoryRepo)),
	wire.Bind(new(bdspro_internal_repo.ProductMediaRepo), new(*bdspro_infra_postgres.GormProductMediaRepo)),
	wire.Bind(new(bdspro_internal_repo.ProductOrganizationRepo), new(*bdspro_infra_postgres.ProductOrganizationPostgres)),
	wire.Bind(new(bdspro_internal_repo.ProductPriceRepo), new(*bdspro_infra_postgres.GormProductPriceRepo)),
	wire.Bind(new(bdspro_internal_repo.ProductPrivateRepo), new(*bdspro_infra_postgres.GormProductPrivateRepo)),
	wire.Bind(new(bdspro_internal_repo.ProjectBuildRepo), new(*bdspro_infra_postgres.PostgreProjectBuild)),
	wire.Bind(new(bdspro_internal_repo.ProjectRepo), new(*bdspro_infra_postgres.PostgreProject)),
	wire.Bind(new(bdspro_internal_repo.PropertyTypeRepo), new(*bdspro_infra_postgres.PostgrePropertyType)),
	wire.Bind(new(bdspro_internal_repo.RecordHistoryRepo), new(*bdspro_infra_postgres.PostgreReportHistory)),
	wire.Bind(new(bdspro_internal_repo.RegionRepo), new(*bdspro_infra_postgres.PostgreRegion)),
	wire.Bind(new(bdspro_internal_repo.SharingAccessRepo), new(*bdspro_infra_postgres.SharingAccessPostgre)),
	wire.Bind(new(bdspro_internal_repo.UProductChildRepo), new(*bdspro_infra_postgres.PostgreProductChild)),
	wire.Bind(new(bdspro_internal_repo_admin.AdminAssetRepo), new(*bdspro_infra_postgres_admin.AdminAssetPostgres)),
	wire.Bind(new(bdspro_internal_repo_admin.AdminPostRepo), new(*bdspro_infra_postgres_admin.AdminPostPostgres)),
	wire.Bind(new(bdspro_internal_repo_admin.AdminProductRepo), new(*bdspro_infra_postgres_admin.AdminProductPostgres)),
	wire.Bind(new(bdspro_internal_repo_admin.AdminProjectRepo), new(*bdspro_infra_postgres_admin.AdminProjectPostgres)),
	wire.Bind(new(bdspro_internal_repo_admin.AdminPropertyTypeRepo), new(*bdspro_infra_postgres_admin.AdminPropertyTypePostgres)),
	wire.Bind(new(bdspro_internal_usecases.PlanUsecase), new(*bdspro_infra_handler.MemberPlanUsecase)),
	common_injection.NewHttpClient,
	common_utils.NewSyncUtil,
	bdspro_infra_postgres.NewActionRepo,
	bdspro_infra_handler.NewAdminAreaRegionHandler,
	bdspro_infra_handler_admin.NewAdminAssetHandler,
	bdspro_infra_postgres_admin.NewAdminAssetPostgres,
	bdspro_internal_usecases_admin.NewAdminAssetUsecase,
	bdspro_infra_handler_admin.NewAdminPostHandler,
	bdspro_infra_postgres_admin.NewAdminPostPostgres,
	bdspro_internal_usecases_admin.NewAdminPostUsecase,
	bdspro_infra_handler_admin.NewAdminProductHandler,
	bdspro_infra_postgres_admin.NewAdminProductPostgres,
	bdspro_internal_usecases_admin.NewAdminProductUsecase,
	bdspro_infra_handler_admin.NewAdminProjectHandler,
	bdspro_infra_postgres_admin.NewAdminProjectPostgres,
	bdspro_internal_usecases_admin.NewAdminProjectUsecase,
	bdspro_infra_handler_admin.NewAdminPropertyTypeHandler,
	bdspro_infra_postgres_admin.NewAdminPropertyTypePostgres,
	bdspro_internal_usecases_admin.NewAdminPropertyTypeUsecase,
	bdspro_infra_handler.NewAdminRegionHandler,
	bdspro_infra_handler_admin.NewAdminTransactionHandler,
	bdspro_infra_mapper.NewAdminTransactionMapper,
	bdspro_infra_postgres_admin.NewAdminTransactionPostgres,
	bdspro_internal_usecases_admin.NewAdminTransactionUsecase,
	bdspro_infra_handler_admin.NewAdminTxHandler,
	bdspro_infra_postgres.NewAmenityRepo,
	bdspro_infra_mapper.NewApartmentAttributeMapper,
	bdspro_infra_mapper.NewApartmentMapper,
	bdspro_internal_usecases_shared.NewApartmentUsecase,
	bdspro_infra_mapper.NewAreaRegionMapper,
	bdspro_infra_postgres.NewAreaRegionPostgres,
	bdspro_infra_postgres.NewAreaRegionRepo,
	bdspro_internal_usecases_admin.NewAreaRegionUsecase,
	bdspro_infra_mapper.NewAssetCostMapper,
	bdspro_infra_handler.NewAssetCostService,
	bdspro_infra_handler.NewAssetCostTypeServer,
	bdspro_internal_usecases_shared.NewAssetCostTypeUsecase,
	bdspro_internal_usecases_shared.NewAssetCostUsecase,
	bdspro_infra_validator.NewAssetCostValidator,
	bdspro_internal_job.NewAssetDashboardStatsJob,
	bdspro_infra_mapper.NewAssetExploitationMapper,
	bdspro_infra_handler.NewAssetExploitationServer,
	bdspro_internal_usecases_shared.NewAssetExploitationUc,
	bdspro_infra_validator.NewAssetExploitationValidator,
	bdspro_infra_handler.NewAssetIncomeTypeServer,
	bdspro_internal_usecases.NewAssetIncomeTypeUc,
	bdspro_infra_mapper.NewAssetLegalMapper,
	bdspro_infra_handler.NewAssetLegalServer,
	bdspro_internal_usecases.NewAssetLegalUc,
	bdspro_infra_mapper.NewAssetMapper,
	bdspro_infra_postgres.NewAssetShareRepo,
	bdspro_infra_router_user.NewAssetShareRouter,
	bdspro_internal_usecases.NewAssetShareUC,
	bdspro_infra_postgres_audit.NewAuditLogRepository,
	bdspro_infra_client.NewAuthClient,
	bdspro_infra_rpc.NewAuthRPCClient,
	bdspro_infra_mapper.NewBankAccountMapper,
	bdspro_infra_postgres.NewBankAccountPostgresRepository,
	bdspro_infra_handler.NewBdsDomainHandler,
	bdspro_infra_mapper.NewBdsDomainMapper,
	bdspro_infra_postgres.NewBdsDomainPostgres,
	bdspro_internal_usecases.NewBdsDomainUsecase,
	bdspro_infra_handler.NewBdsproDashboardHandler,
	bdspro_infra_handler.NewBdsproPublicService,
	bdspro_infra_mapper.NewBuildMapper,
	bdspro_infra_postgres.NewBuildingInfoRepo,
	bdspro_infra_rpc.NewCRMRPCClient,
	bdspro_infra_rpc.NewChatRPCClient,
	bdspro_infra_redis.NewClient,
	bdspro_infra_providers.NewCodeDataUsecase,
	bdspro_infra_mapper.NewCommonMapper,
	bdspro_infra_mapper.NewContractDealMapper,
	bdspro_infra_validator.NewContractDealValidator,
	bdspro_infra_handler.NewCostDocumentServer,
	bdspro_internal_usecases.NewCostDocumentUc,
	bdspro_infra_mapper.NewCostTypeMapper,
	bdspro_infra_postgres.NewCostTypeRepository,
	bdspro_internal_usecases.NewCostTypeUsecase,
	bdspro_infra_validator.NewCostTypeValidator,
	bdspro_internal_usecases.NewDashboardUsecase,
	bdspro_infra_handler.NewDealCommissionHandler,
	bdspro_infra_mapper.NewDealCommissionTransformer,
	bdspro_internal_usecases.NewDealCommissionUsecase,
	bdspro_infra_validator.NewDealCommissionValidator,
	bdspro_internal_usecases.NewDealContractUsecase,
	bdspro_infra_handler.NewDealCostHandler,
	bdspro_infra_mapper.NewDealCostMapper,
	bdspro_infra_postgres.NewDealCostRepository,
	bdspro_internal_usecases.NewDealCostUsecase,
	bdspro_infra_validator.NewDealCostValidator,
	bdspro_infra_handler.NewDealHandler,
	bdspro_infra_handler.NewDealInvestmentHandler,
	bdspro_infra_handler.NewDealInvitationHandler,
	bdspro_infra_mapper.NewDealInvitationTransformer,
	bdspro_internal_usecases.NewDealInvitationUsecase,
	bdspro_infra_validator.NewDealInvitationValidator,
	bdspro_infra_postgres.NewDealMemberPostgresRepository,
	bdspro_infra_handler.NewDealMilestoneHandler,
	bdspro_infra_postgres.NewDealMilestonePostgresRepository,
	bdspro_infra_mapper.NewDealMilestoneTransformer,
	bdspro_internal_usecases.NewDealMilestoneUsecase,
	bdspro_infra_validator.NewDealMilestoneValidator,
	bdspro_infra_postgres.NewDealOfBranchPostgres,
	bdspro_infra_postgres.NewDealOfGroupPostgres,
	bdspro_infra_postgres.NewDealOfOrganizationPostgres,
	bdspro_infra_postgres.NewDealTransactionPostgresRepository,
	bdspro_internal_usecases.NewDealUsecase,
	bdspro_infra_client.NewDeepseekClient,
	bdspro_infra_mapper.NewDepositeMapper,
	bdspro_infra_mapper.NewDeveloperMapper,
	bdspro_internal_repo.NewDeveloperRepo,
	bdspro_infra_handler.NewDistributionHandler,
	bdspro_infra_mapper.NewDistributionMapper,
	bdspro_infra_postgres.NewDistributionPostgres,
	bdspro_internal_usecases.NewDistributionUsecase,
	bdspro_infra_mapper.NewDocumentMapper,
	bdspro_infra_postgres.NewDocumentPostgresRepository,
	bdspro_internal_usecases.NewEventHistoryUsecase,
	bdspro_infra_postgres.NewEvidenceRepo,
	bdspro_infra_postgres.NewExternalRefRepo,
	bdspro_infra_postgres.NewGormAssetCostRepo,
	bdspro_infra_postgres.NewGormAssetIncomeTypeRepo,
	bdspro_infra_postgres.NewGormAssetLegalRepo,
	bdspro_infra_postgres.NewGormCostDocumentRepo,
	bdspro_infra_postgres.NewGormHouseInfoRepo,
	bdspro_infra_postgres.NewGormIncomeDocumentRepo,
	bdspro_infra_postgres.NewGormPostMediaRepo,
	bdspro_infra_postgres.NewGormPostRepo,
	bdspro_infra_postgres.NewGormProductMediaRepo,
	bdspro_infra_postgres.NewGormProductPriceRepo,
	bdspro_infra_postgres.NewGormProductPrivateRepo,
	bdspro_infra_postgres.NewGormUserProductRepo,
	bdspro_infra_postgres.NewGroupDealPostgresRepository,
	bdspro_infra_mapper.NewGroupDealTransformer,
	bdspro_infra_validator.NewGroupDealValidator,
	bdspro_infra_handler.NewGrpcAssetService,
	bdspro_infra_handler.NewGrpcPostService,
	bdspro_infra_mapper.NewHistoryMapper,
	bdspro_infra_client.NewHubClient,
	bdspro_infra_rpc.NewHubRPCClient,
	bdspro_infra_handler.NewIdentifierHandler,
	bdspro_infra_mapper.NewIdentifierMapper,
	bdspro_infra_postgres.NewIdentifierRepository,
	bdspro_internal_usecases.NewIdentifierUsecase,
	bdspro_internal_modules.NewImpactDetectionEngine,
	bdspro_infra_handler.NewIncomeDocumentServer,
	bdspro_internal_usecases.NewIncomeDocumentUc,
	bdspro_infra_postgres.NewInfoRepo,
	bdspro_initial.NewInitialApp,
	bdspro_infra_postgre.NewIntentPostgres,
	bdspro_internal_usecases.NewIntentUsecase,
	bdspro_infra_handler.NewInternalHandler,
	bdspro_infra_handler.NewInternalNoteHandler,
	bdspro_infra_postgres.NewInternalNotePostgresRepository,
	bdspro_infra_mapper.NewInternalNoteTransformer,
	bdspro_internal_usecases.NewInternalNoteUsecase,
	bdspro_infra_validator.NewInternalNoteValidator,
	bdspro_infra_handler.NewInternalTransactionHandler,
	bdspro_infra_mapper.NewInvestmentMapper,
	bdspro_infra_postgres.NewInvestmentPostgres,
	bdspro_internal_usecases.NewInvestmentUsecase,
	bdspro_infra_validator.NewInvestmentValidator,
	bdspro_infra_postgres.NewLandInfoRepo,
	bdspro_infra_postgres.NewLineageRepo,
	bdspro_infra_router_user.NewListRouter,
	bdspro_internal_usecases.NewListUsecase,
	bdspro_internal_usecases.NewLoanPaymentUsecase,
	bdspro_infra_postgres.NewLocationRepo,
	bdspro_infra_postgres.NewMediaRepo,
	bdspro_infra_providers.NewMemberPlanService,
	bdspro_infra_handler.NewMemberPlanUsecase,
	bdspro_infra_client.NewNotificationClient,
	bdspro_infra_rpc.NewNotificationRPCClient,
	bdspro_infra_router_org.NewOrgAssetCostRouter,
	bdspro_infra_router_org.NewOrgAssetExploitationRouter,
	bdspro_infra_router_org.NewOrgAssetRouter,
	bdspro_infra_router_org.NewOrgCostTypeRouter,
	bdspro_infra_router_org.NewOrgPostRoute,
	bdspro_infra_router_org.NewOrgProductChildRouter,
	bdspro_infra_client.NewOrganizationClient,
	bdspro_infra_rpc.NewOrganizationRPCClient,
	bdspro_infra_client.NewPaymentClient,
	bdspro_infra_rpc.NewPaymentRPCClient,
	bdspro_internal_job.NewPostDashboardStatsJob,
	bdspro_infra_mapper.NewPostMapper,
	bdspro_infra_router_user.NewPostMediaRoute,
	bdspro_infra_postgres.NewPostgreApartmentRepo,
	bdspro_infra_postgres.NewPostgreAsset,
	bdspro_infra_postgres.NewPostgreAssetExploitation,
	bdspro_infra_postgres.NewPostgreAssetOrganization,
	bdspro_infra_postgres.NewPostgreAssetUser,
	bdspro_infra_postgres.NewPostgreDocType,
	bdspro_infra_postgres.NewPostgreHistoryRepo,
	bdspro_infra_postgres.NewPostgrePostOrganization,
	bdspro_infra_postgres.NewPostgrePostUser,
	bdspro_infra_postgres.NewPostgreProductChildRepo,
	bdspro_infra_postgres.NewPostgreProductNoteRepo,
	bdspro_infra_postgres.NewPostgreProject,
	bdspro_infra_postgres.NewPostgreProjectBuild,
	bdspro_infra_postgres.NewPostgrePropertyAmenityRepo,
	bdspro_infra_postgres.NewPostgrePropertyBuildingInfoRepo,
	bdspro_infra_postgres.NewPostgrePropertyEdvidenceRepo,
	bdspro_infra_postgres.NewPostgrePropertyExternalRefRepo,
	bdspro_infra_postgres.NewPostgrePropertyIdentifyRepo,
	bdspro_infra_postgres.NewPostgrePropertyInfoRepo,
	bdspro_infra_postgres.NewPostgrePropertyLandInfoRepo,
	bdspro_infra_postgres.NewPostgrePropertyLocationRepo,
	bdspro_infra_postgres.NewPostgrePropertyMediaRepo,
	bdspro_infra_postgres.NewPostgrePropertyProductRepo,
	bdspro_infra_postgres.NewPostgrePropertyRelationRepo,
	bdspro_infra_postgres.NewPostgrePropertyRepo,
	bdspro_infra_postgres.NewPostgrePropertyStatisticRepo,
	bdspro_infra_postgres.NewPostgrePropertyType,
	bdspro_infra_postgres.NewPostgreRegion,
	bdspro_infra_postgres.NewPostgreReportHistory,
	bdspro_infra_postgres.NewPostgreUserCostType,
	bdspro_infra_postgres.NewProductAssetPostgres,
	bdspro_internal_usecases.NewProductAssetUsecase,
	bdspro_internal_job.NewProductDashboardStatsJob,
	bdspro_infra_mapper.NewProductMapper,
	bdspro_infra_handler.NewProductNoteHandler,
	bdspro_infra_mapper.NewProductNoteMapper,
	bdspro_internal_usecases.NewProductNoteUsecase,
	bdspro_infra_postgres.NewProductOfOrgPostgres,
	bdspro_infra_mapper.NewProductPriceMapper,
	bdspro_infra_handler.NewProductService,
	bdspro_internal_usecases_shared.NewProductUsecase,
	bdspro_infra_postgres.NewProductUserPostgres,
	bdspro_infra_validator.NewProductValidator,
	bdspro_infra_mapper.NewProjectBuildMapper,
	bdspro_infra_handler.NewProjectBuildService,
	bdspro_internal_usecases.NewProjectBuildUsecase,
	bdspro_infra_mapper.NewProjectMapper,
	bdspro_infra_handler_property.NewPropertyHandler,
	bdspro_infra_mapper.NewPropertyMapper,
	bdspro_infra_postgres.NewPropertyReportRepository,
	bdspro_infra_mapper.NewPropertyTypeMapper,
	bdspro_internal_usecases.NewPropertyTypeUsecase,
	bdspro_internal_usecases_property.NewPropertyUsecase,
	bdspro_infra_postgres.NewPropertyUserPostgres,
	bdspro_infra_postgres.NewProvinceV2Repository,
	bdspro_infra_mapper.NewPublicMapper,
	bdspro_infra_router_public.NewPublicRouter,
	bdspro_infra_postgres_audit.NewPushRepo,
	bdspro_internal_usecases.NewRecordHistoryUsecase,
	bdspro_infra_mapper.NewRegionMapper,
	bdspro_internal_usecases_admin.NewRegionUsecase,
	bdspro_internal_usecases_shared.NewRequestUsecase,
	bdspro_infra_router_user.NewRouterManager,
	bdspro_internal_modules.NewRuleEngine,
	bdspro_internal_usecases_shared.NewShareAccessUsecase,
	bdspro_internal_usecases_shared.NewSharedAssetUsecase,
	bdspro_internal_usecases_shared.NewSharedPostUsecase,
	bdspro_infra_mapper.NewSharingAccessMapper,
	bdspro_infra_postgres.NewSharingAccessPostgre,
	bdspro_infra_handler.NewSharingAccessService,
	bdspro_infra_validator.NewSharingAccessValidator,
	bdspro_internal_modules.NewSnapshotComparator,
	bdspro_infra_postgres.NewSnapshotRepository,
	bdspro_infra_rpc.NewTQDRPCClient,
	bdspro_infra_postgres.NewTransactionActionPostgresRepository,
	bdspro_infra_validator.NewTransactionActionValidator,
	bdspro_infra_postgres.NewTransactionGorm,
	bdspro_infra_handler.NewTransactionHandler,
	bdspro_infra_postgres.NewTransactionPostgresRepository,
	bdspro_internal_usecases.NewTransactionUsecase,
	bdspro_infra_validator.NewTransactionValidator,
	bdspro_internal_usecases.NewTransferTaxFeeUsecase,
	bdspro_infra_handler.NewTxContractDealHandler,
	bdspro_infra_handler.NewTxCostTypeHandler,
	bdspro_infra_mapper.NewTxCostTypeMapper,
	bdspro_infra_handler.NewTxHandler,
	bdspro_infra_mapper.NewTxMapper,
	bdspro_infra_router_user.NewUAssetLegalRoute,
	bdspro_internal_usecases.NewUPostMediaUsecase,
	bdspro_infra_router_user.NewUProductAccessRouter,
	bdspro_infra_router_user.NewUserAssetCostRouter,
	bdspro_infra_router_user.NewUserAssetExploitationRouter,
	bdspro_infra_router_user.NewUserAssetRouter,
	bdspro_infra_client.NewUserClient,
	bdspro_infra_router_user.NewUserCostTypeRouter,
	bdspro_infra_router_user.NewUserPostRoute,
	bdspro_infra_router_user.NewUserProductChildRouter,
	bdspro_infra_router_user.NewUserProductRouter,
	bdspro_infra_router_user.NewUserProjectBuildRouter,
	bdspro_infra_rpc.NewUserRPCClient,
	bdspro_infra_postgres_audit.NewVersionRepo,
	bdspro_infra_postgres.NewWardV2Repository,
)

func InitializeApp() (*bdspro_initial.InitialApp, func(), error) {
	wire.Build(wireSet)
	return nil, nil, nil
}
