// Package hub Code generated by swaggo/swag. DO NOT EDIT
package hub

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event-queue": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới một event queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Tạo mới event queue",
                "parameters": [
                    {
                        "description": "Thông tin event queue",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hubpb.EventQueueSaveDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/event-queue/detail/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin chi tiết của một event queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Lấy chi tiết event queue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của event queue",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/event-queue/edit/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật thông tin event queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Cập nhật event queue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của event queue",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin event queue",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hubpb.EventQueueSaveDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/event-queue/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách event queue với phân trang và filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Lấy danh sách event queue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Kích thước trang",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tìm kiếm theo tên hoặc loại event",
                        "name": "text",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Profile ID",
                        "name": "profileId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Trạng thái (10: Pending, 20: Processing, 30: Completed, 40: Failed, 50: Cancelled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Loại event",
                        "name": "eventType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Từ ngày (YYYY-MM-DD)",
                        "name": "fromDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Đến ngày (YYYY-MM-DD)",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/event-queue/status/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật trạng thái của event queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Cập nhật trạng thái event queue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của event queue",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin trạng thái",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hubpb.EventQueueStatusDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/event-queue/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xóa mềm event queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Queue"
                ],
                "summary": "Xóa event queue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của event queue",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/health": {
            "get": {
                "description": "Kiểm tra trạng thái service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal"
                ],
                "summary": "Health check",
                "responses": {}
            }
        },
        "/v2/hub/districts": {
            "get": {
                "description": "Lấy danh sách quận/huyện, hỗ trợ lọc theo tỉnh và tìm kiếm theo tên",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Lấy danh sách quận/huyện",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mã tỉnh/thành phố để lọc",
                        "name": "provinceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Từ khóa tìm kiếm theo tên",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hubpb.GetDistrictsResponse"
                        }
                    }
                }
            }
        },
        "/v2/hub/provinces": {
            "get": {
                "description": "Lấy danh sách tất cả các tỉnh/thành phố, hỗ trợ tìm kiếm theo tên",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Lấy danh sách tỉnh/thành phố",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Từ khóa tìm kiếm theo tên",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hubpb.GetProvincesResponse"
                        }
                    }
                }
            }
        },
        "/v2/hub/wards": {
            "get": {
                "description": "Lấy danh sách phường/xã, hỗ trợ lọc theo quận và tìm kiếm theo tên",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Lấy danh sách phường/xã",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mã quận/huyện để lọc",
                        "name": "districtId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Từ khóa tìm kiếm theo tên",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hubpb.GetWardsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hubpb.District": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "provinceId": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "typeText": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "hubpb.EventQueueSaveDTO": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "eventData": {
                    "type": "string"
                },
                "eventName": {
                    "type": "string"
                },
                "eventType": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "maxRetries": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "integer"
                },
                "profileId": {
                    "type": "integer"
                },
                "retryCount": {
                    "type": "integer"
                },
                "scheduledAt": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "hubpb.EventQueueStatusDTO": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "hubpb.GetDistrictsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hubpb.District"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "hubpb.GetProvincesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hubpb.Province"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "hubpb.GetWardsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hubpb.Ward"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "hubpb.Province": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "typeText": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "hubpb.Ward": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "districtId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "typeText": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2/utility",
	Schemes:          []string{},
	Title:            "Utility API",
	Description:      "API cho utility service, bao gồm event-queue và các tiện ích khác",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
