// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"common/db"
	"common/injection"
	"common/redis"
	"common/utils"
	"github.com/google/wire"
	"gorm.io/gorm"
	"notification/config"
	"notification/infra/cache"
	"notification/infra/client"
	"notification/infra/firebase"
	"notification/infra/handler"
	"notification/infra/mapper"
	"notification/infra/postgres"
	"notification/initial"
	"notification/internal/dto"
	"notification/internal/usecase"
	"pb/clients"
)

// Injectors from wire.go:

func InitializeApp(database *gorm.DB, redisService *_redis.RedisService, userRPC *clients.UserGrpcClient, firebaseConfig *config.FirebaseConfig) (*initial.InitialApp, func(), error) {
	notificationStore := postgres.NewPostgreNotification(database)
	redisClient := cache.NewRedisClient(redisService)
	authClient := client.NewAuthClient(userRPC)
	firebaseProvider := firebase.NewFirebaseService(firebaseConfig, database)
	notificationUsecase := usecase.NewNotificationService(notificationStore, redisClient, authClient, firebaseProvider)
	notificationMapper := mapper.NewNotificationMapper()
	adminHistoryStore := postgres.NewAdminHistoryPostgres(database)
	userProfileReader := client.NewUserClient(userRPC)
	adminHistoryUsecase := usecase.NewAdminHistoryUsecase(adminHistoryStore, userProfileReader)
	adminHistoryMapper := mapper.NewAdminHistoryMapper()
	dealHistoryStore := postgres.NewDealHistoryPostgres(database)
	dealHistoryUsecase := usecase.NewDealHistoryUsecase(dealHistoryStore)
	historyAuthPostgres := postgres.NewHistoryAuthPostgres(database)
	historyAuthUsecase := usecase.NewHistoryAuthUsecase(historyAuthPostgres)
	historyAuthMapper := mapper.NewHistoryAuthMapper()
	personConfigPostgres := postgres.NewPersonConfigPostgres(database)
	personConfigUsecase := usecase.NewPersonConfigUsecase(personConfigPostgres)
	propertyHistoryStore := postgres.NewActivityHistoryPostgres(database)
	propertyHistoryUseCase := usecase.NewPropertyHistoryUseCase(propertyHistoryStore, userProfileReader)
	internalHandler := handler.NewInternalHandler(notificationUsecase, notificationMapper, adminHistoryUsecase, adminHistoryMapper, dealHistoryUsecase, historyAuthUsecase, historyAuthMapper, personConfigUsecase, propertyHistoryUseCase)
	accountWarningPostgresRepo := postgres.NewAccountWarningPostgresRepo(database)
	accountWarningUsecase := usecase.NewAccountWarningUsecase(accountWarningPostgresRepo)
	syncUtil := _utils.NewSyncUtil(redisService)
	notificationHandler := handler.NewNotificationHandler(notificationUsecase, adminHistoryUsecase, adminHistoryMapper, accountWarningUsecase, userProfileReader, notificationMapper, syncUtil)
	historyStore := postgres.NewHistoryRepo(database)
	historyUsecase := usecase.NewHistoryUsecase(historyStore)
	historyMapper := mapper.NewHistoryMapper()
	historyHandler := handler.NewHistoryHandler(historyUsecase, historyMapper, historyAuthUsecase, historyAuthMapper)
	dealHistoryHandler := handler.NewDealHistoryHandler(dealHistoryUsecase)
	propertyHistoryHandler := handler.NewPropertyHistoryHandler(propertyHistoryUseCase, syncUtil)
	initialApp := initial.NewInitialApp(internalHandler, notificationHandler, historyHandler, dealHistoryHandler, propertyHistoryHandler)
	return initialApp, func() {
	}, nil
}

// wire.go:

var wireSet = wire.NewSet(_db.NewTransactionRepo, wire.Bind(new(usecase.PushTokenResolver), new(*client.AuthClient)), wire.Bind(new(usecase.PushSender), new(*firebase.FirebaseProvider)), wire.Bind(new(usecase.AccountWarningStore), new(*postgres.AccountWarningPostgresRepo)), wire.Bind(new(usecase.HistoryAuthStore), new(*postgres.HistoryAuthPostgres)), wire.Bind(new(usecase.PersonConfigStore), new(*postgres.PersonConfigPostgres)), injection.NewHttpClient, _utils.NewSyncUtil, cache.NewRedisClient, postgres.NewAccountWarningPostgresRepo, usecase.NewAccountWarningUsecase, postgres.NewActivityHistoryPostgres, mapper.NewAdminHistoryMapper, postgres.NewAdminHistoryPostgres, usecase.NewAdminHistoryUsecase, client.NewAuthClient, handler.NewDealHistoryHandler, postgres.NewDealHistoryPostgres, usecase.NewDealHistoryUsecase, firebase.NewFirebaseService, mapper.NewHistoryAuthMapper, postgres.NewHistoryAuthPostgres, usecase.NewHistoryAuthUsecase, handler.NewHistoryHandler, mapper.NewHistoryMapper, postgres.NewHistoryRepo, postgres.NewHistoryRepository, usecase.NewHistoryUsecase, initial.NewInitialApp, handler.NewInternalHandler, handler.NewNotificationHandler, mapper.NewNotificationMapper, usecase.NewNotificationService, postgres.NewPersonConfigPostgres, usecase.NewPersonConfigUsecase, postgres.NewPostgreNotification, handler.NewPropertyHistoryHandler, mapper.NewPropertyHistoryMapper, usecase.NewPropertyHistoryUseCase, dto.NewSendNotiResponse, client.NewUserClient)
