BEGIN;

DELETE FROM role_permissions
WHERE permission_id IN (SELECT id FROM permissions WHERE key IN (
    'COMMERCIAL_SUBSCRIPTION_VIEW', 'PAYMENT_ORDER_VIEW',
    'PAYMENT_FULFILLMENT_VIEW', 'PAYMENT_FULFILLMENT_REDRIVE'
));
DELETE FROM group_permissions
WHERE permission_id IN (SELECT id FROM permissions WHERE key IN (
    'COMMERCIAL_SUBSCRIPTION_VIEW', 'PAYMENT_ORDER_VIEW',
    'PAYMENT_FULFILLMENT_VIEW', 'PAYMENT_FULFILLMENT_REDRIVE'
));
DELETE FROM permissions
WHERE key IN (
    'COMMERCIAL_SUBSCRIPTION_VIEW',
    'PAYMENT_ORDER_VIEW',
    'PAYMENT_FULFILLMENT_VIEW',
    'PAYMENT_FULFILLMENT_REDRIVE'
);

COMMIT;
