// Code generated by mockery. DO NOT EDIT.
package mock_repo

import (
	context "context"
	qh_domain "tqd/internal/domain/qh"
	enums "tqd/internal/enums"
	repo "tqd/internal/interface/repo"

	mock "github.com/stretchr/testify/mock"
)

type MockLayerRepository struct {
	mock.Mock
}

func (m *MockLayerRepository) Create(ctx context.Context, layer *qh_domain.QHLayer, replaceLayerIDs []uint64, updatedBy uint64) error {
	args := m.Called(ctx, layer, replaceLayerIDs, updatedBy)
	return args.Error(0)
}

func (m *MockLayerRepository) Delete(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockLayerRepository) GetByID(ctx context.Context, id uint64) (*qh_domain.QHLayer, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*qh_domain.QHLayer), args.Error(1)
}

func (m *MockLayerRepository) GetByName(ctx context.Context, name string) (*qh_domain.QHLayer, error) {
	args := m.Called(ctx, name)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*qh_domain.QHLayer), args.Error(1)
}

func (m *MockLayerRepository) List(ctx context.Context, filter *repo.LayerFilter) ([]qh_domain.QHLayer, int64, error) {
	args := m.Called(ctx, filter)
	return args.Get(0).([]qh_domain.QHLayer), args.Get(1).(int64), args.Error(2)
}

func (m *MockLayerRepository) ListClient(ctx context.Context, filter *repo.ClientLayerFilter) ([]qh_domain.QHLayer, int64, error) {
	args := m.Called(ctx, filter)
	return args.Get(0).([]qh_domain.QHLayer), args.Get(1).(int64), args.Error(2)
}

func (m *MockLayerRepository) Update(ctx context.Context, layer *qh_domain.QHLayer) error {
	args := m.Called(ctx, layer)
	return args.Error(0)
}

func (m *MockLayerRepository) UpdateStatus(ctx context.Context, id uint64, status enums.LayerStatus) error {
	args := m.Called(ctx, id, status)
	return args.Error(0)
}

func (m *MockLayerRepository) UpdateVisibility(ctx context.Context, id uint64, visible int32) error {
	args := m.Called(ctx, id, visible)
	return args.Error(0)
}

func (m *MockLayerRepository) UpdateImportStatus(ctx context.Context, id uint64, st enums.LayerImportStatus, importBatchID *string) error {
	args := m.Called(ctx, id, st, importBatchID)
	return args.Error(0)
}

func (m *MockLayerRepository) GetByImportBatchID(ctx context.Context, batchID string) (*qh_domain.QHLayer, error) {
	args := m.Called(ctx, batchID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*qh_domain.QHLayer), args.Error(1)
}

func (m *MockLayerRepository) ResetLayerImportTracking(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}
